### ISSUE TITLE
Improve minidump Integrations (SentryMinidump, ElectronMinidump)

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry-electron#1009]
### Problem Statement

The [SentryMinidump](https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/sentryminidump/) integration can invoke beforeSend or ignoreErrors at the time of crash, but can't send Main thread mindumps until the crashed application is restored, meaning users who do not restart their app will not send a minidump ([Link](https://github.com/getsentry/sentry-electron/issues/370#issue-1014376411)). [ElectronMinidump](https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/electronminidump/) can send Main thread minidumps right away, but can't invoke beforeSend or ignoreErrors at the time of the crash.

### Solution Brainstorm

Currently there isn't a way to both a) capture Main thread minidumps and send right away, AND b) allow callback methods to be invoked before sending to Sentry. Allowing one or both Mindiump integrations for Electron would ensure crashes are sent to Sentry while being subject to callback methods.

**Comment by timfish** [comment]
The `sentryMinidumpIntegration` works by disabling server upload in Electrons `crashReporter`. The  `crashReporter` then leaves us to manage the minidump files in a directory. 

The `electronMinidumpIntegration` leaves the `crashReporter` with server upload enabled and Electrons native crash reporter manages the files. They are often not on disk long enough to be read from JavaScript.

These two modes can't be used together because they both rely of having complete control of the generated minidumps files.

**Comment by AbhiPrasad** [comment]
Given we've discussed this also in slack/discord, I'm going to mark this as not planned for the time being.

If there is a specific improvement to be made with a solution in mind, we can re-open this issue and investigate further.
