### ISSUE TITLE
Additional information is only guid

### ISSUE THREAD

**Issue by BlackHole1** [getsentry/sentry-electron#110]
![image](https://user-images.githubusercontent.com/8198408/45079396-13dda800-b125-11e8-8fbc-c3094f44b668.png)

Strangely enough, other logs are OK. The normal information should be the following:
![image](https://user-images.githubusercontent.com/8198408/45079578-864e8800-b125-11e8-93cd-6d6664e32808.png)

The field information of GUID is not found in our code.

I want to ask, under what circumstances will this problem arise?

Thank you very much.

**Comment by HazAT** [comment]
That's a really good question, we also do not set `guid` in our SDK.
Can you link me to your issue in Sentry?
Also are you using the latest version?

**Comment by BlackHole1** [comment]
I am using the latest version, What I want to ask is, why is it only the guid field, no other information?

**Comment by jan-auer** [comment]
@BlackHole1 I assume you see these additional fields in native crashes reported by sentry-electron, as opposed to native crashes? In any case, these fields are set by the underlying Electron Crash Reporter.  Also, an update of Electron might have lead to different behavior here. 

Most of that information should also show up in the other contexts (see the groups at the top). If you are missing any critical debugging information, please let us know which versions of Electron and the SDK you are using and ideally let us know, which Sentry organization you are on.

I am closing this for now, as it is expected behavior. We do not guarantee any of the additional attributes. Feel free to share more information if you lack critical information and we will re-open. 

Thanks!
