### ISSUE TITLE
 EPERM: operation not permitted, open '....node_modules\win-ca\pem\roots.pem'

### ISSUE THREAD

**Issue by koenoe** [getsentry/sentry-electron#204]
- [ ] SKD version - `@sentry/electron@v1.1.0`
- [ ] Electron version - `electron@v7.1.5`
- [ ] Platform - `Windows Store`

## Description

Since we upgraded this package from v1.0.0 to v1.1.0 we see a lot of these errors for our Windows Store users:
```
EPERM: operation not permitted, open 'C:\Program Files\WindowsApps\<APP_NAME>.27241E05630EA_2.11.3.0_x86__kn85bz84x7te4\app\resources\app.asar.unpacked\node_modules\win-ca\pem\roots.pem'
```
I noticed in the changelog that you introduced this `win-ca` package in v1.1.0. Looks like [this issue](https://github.com/ukoloff/win-ca/issues/17) might be related?

Is downgrading to v1.0.0 the best solution for now? I couldn't find any open issues, hence why I opened this one.

**Comment by timfish** [comment]
The 1.1.0 release moved from using `electron-fetch` to `node-fetch`+`win-ca`. This was because there have been reoccurring issues with both `electron-fetch` and Electrons own `net` module, the most recent being that `electron-fetch` simply wasn't working with Electron v7. 

Unlike the Electron `net` module, the Node one does not respect root certificates added to the Windows certificate store so the addition of `win-ca` allows HTTPS to work in corporate environments that do deep SSL inspection.

I don't have any experience building or shipping Electron apps for Windows Store. Can you shed some light on why this might be failing? Is the Windows Store environment more restrictive than usual? We are already calling [`require('win-ca/fallback')`](https://github.com/getsentry/sentry-electron/blob/70cdcef280f9455d65a9b4b483db45894cd614df/src/main/uploader.ts#L120) and the docs suggest this should already fallback to saving in `.local/win-ca/pem`. It might be that Windows Store apps do not even allow access to the certificate store but I can't find this documented anywhere.

**Comment by koenoe** [comment]
Only suspicion I have that could cause this is that Windows Store apps are running in a virtualized environment and therefore have restricted access when it comes to reading certificates. Some folders being virtualized, like the %APPDATA& folder for example, could maybe cause issues like this too?

We didn't have issues with it when you didn't use this `win-ca` module though and Sentry implementation seemed to work fine.

**Comment by timfish** [comment]
The virtualisation could certainly be the issue. `win-ca` will apparently attempt a few paths and the virtualisation can give the appearance of writing success but as files don't persist this will then cause issues. I've opened a PR (#206) that makes `win-ca` use the sentry cache path which will hopefully fix this as we know it's writable. I've also made it so that any errors that occur while calling `win-ca` are now ignored as this failure will not impact the vast majority of users.

`electron-fetch` was completely broken for `electron@7` for a couple of months and it has also broken functionality in `sentry-electron` before. It did get fixed to work for `electron@7`, but there are [many unresolved issues](https://github.com/arantes555/electron-fetch/issues/17#issuecomment-553989338) and while these issues are outstanding, it doesn't seem like a great idea to continue to rely on it as a dependency.

**Comment by koenoe** [comment]
That looks good, thank you!

**Comment by koenoe** [comment]
When will it be released?

**Comment by koenoe** [comment]
Any updates on when this will be released?

**Comment by HazAT** [comment]
`1.2.0` is out now
