### ISSUE TITLE
Using @sentry/react inside renderer process

### ISSUE THREAD

**Issue by bermanboris** [getsentry/sentry-electron#295]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v2.2.0`
- [x] Electron version - `electron@v11.2.0`
- [x] Platform - `macOS`

## Description

I would like to know if I can use `@sentry/react` with this library inside renderer process, and if so, then how do I do that?

Thanks!

**Comment by jahglow** [comment]
Good question because I'm struggling getting source mapping work when useing sentry/react since sourcemaps get uploaded but they are resolved against app location on hard drive and even devtools can't resolve them, nor can Sentry do that

**Comment by ash0x0** [comment]
@jahglow @bermanboris Did either of you find a good solution to this?

**Comment by jahglow** [comment]
I eventually set off using sentry react for error logging since most of
changes are in the react part while electron one stays mostly intact. I
used their webpack plugin for sourcemaps uploading which is nearly
zero-config and works well with local builds as well as gitlab CI builds.
Had to rewire paths in the onbeforesend to make the error and sourcemaps
stacktrace paths match, probably there was a better way but I got tired of
searching.

сб, 27 февр. 2021 г., 18:04 Ahmed Elshafey <notifications@github.com>:

**Comment by timfish** [comment]
I've been looking into this myself recently and since the `@sentry/react` initialisation is just a thin wrapper around `@sentry/browser` [with the SDK information overwritten](https://github.com/getsentry/sentry-javascript/blob/master/packages/react/src/sdk.ts), the answer seems to be that you should call `init` from `@sentry/electron` and then use `@sentry/react` only for its specific components:
```ts
import React from 'react';
import ReactDOM from "react-dom";
import * as Sentry from '@sentry/electron';

Sentry.init({
  dsn: '__DSN__',
  // ...
});

// ...

ReactDOM.render(<App />, rootNode);
```

```ts
import React from 'react';
import * as Sentry from '@sentry/react';

function FallbackComponent() {
  return (
    <div>An error has occured</div>
  )
}

class App extends React.Component {
  render() {
    return (
      <Sentry.ErrorBoundary fallback={FallbackComponent} showDialog>
        <OtherComponents />
      </Sentry.ErrorBoundary>
    )
  }
}

export default App;
```

If you find anything that doesn't work, please open a new issue detailing exactly what doesn't work!
