### ISSUE TITLE
Sentry shows simple console.log string as array

### ISSUE THREAD

**Issue by stoefln** [getsentry/sentry-electron#407]
This is just about how the console.log breadcrumbs are formated:
When I do a simple `console.log('UndoManager: startGroupIfNeeded')`, this is how Sentry currently the breadcrumb in the list:

<img width="917" alt="Screenshot 2022-01-10 at 09 25 49" src="https://user-images.githubusercontent.com/562800/148736730-d94cf384-b4fe-437f-968c-d8969a8468de.png">

This blows up the list quite a bit. Is there something I can do about it?

For example: 
https://sentry.io/organizations/stephan-petzl/issues/2874816070/?environment=production&environment=development&project=1554144&query=release%3ARepeato-1.0.0-beta.19%2A+is%3Aunresolved&statsPeriod=14d

## Versions + Platform

SDK version: `@sentry/electron@v2.5.4`
Electron version:  `electron@v12.2.3`
Platforms:  `Windows/macOS/Linux`

**Comment by AbhiPrasad** [comment]
This renders this way because we pass stuff into the data field of the breadcrumb in the SDK. 

I think it's a reasonable ask to try to improve the UI though (perhaps by hiding the data if a user configures it that way?). @stoefln mind opening an [issue in the main Sentry repo](https://github.com/getsentry/sentry/issues/new/choose) to see what the Sentry frontend folks think? We can also see what design thinks there as well!

**Comment by timfish** [comment]
Closing in favour of linked Sentry issue.
