### ISSUE TITLE
SDK delays the electron ready event by ~500ms

### ISSUE THREAD

**Issue by toxik** [getsentry/sentry-electron#421]
## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.0`
- [x] Electron version - `electron@v16.0.6`
- [x] Platform - `Windows & macOS & Linux`

## Description

As the title says, when calling `init` from `@sentry/electron/main` the Electron's `ready` event is delayed by approximately 500ms.
I'm on a Mac mini (2018) 3,2GHz 6-Core Intel Core i7 with 32GB of RAM.

**Comment by timfish** [comment]
Thanks for the report. I'll do some profiling and track it down!

**Comment by timfish** [comment]
Are you bundling your main process code?

It looks like the Node SDK `init` takes 1 second on my machine but if I bundle the main process code into a single JavaScript file, that time goes down to under 30ms.

This is almost certainly caused by all the SDK files being loaded individually by `require`. This causes app startup to be IO bound as the dependency tree is loaded. Once the app is bundled this overhead disappears completely. Production Electron apps should have the main process code bundled for best startup performance.

I suppose we could pre-bundle the Electron SDK to improve this?

**Comment by toxik** [comment]
Yes, everything is bundled.

I was thinking of calling `init` after the app bootstraps and tried using the [Classic protocol ](https://github.com/getsentry/sentry-electron/blob/master/src/main/ipc.ts#L99) but the Renderer doesn't like it (I get the `failed to establish connection` error in the browser)

**Comment by timfish** [comment]
> if I bundle the main process code into a single JavaScript file...

Actually, my previous measurements were flawed. I will continue to profile!

> I was thinking of calling init after the app bootstraps

You could do this but you'd miss any errors/crashes/sessions before the SDK is started.

> the Renderer doesn't like it

If you use Electron IPC and are bundling the main process, you will need to configure a preload script yourself and import the preload code: https://docs.sentry.io/platforms/javascript/guides/electron/#manual-preload

**Comment by toxik** [comment]
Thanks for investigating further!

I did the preloading part per docs but somehow dropping just the `import { IPCChannel } from '@sentry/electron/common';`  line didn't work – we have a `preload.ts` script bundled with webpack.

I manually added the following and now the Renderer is happy though 😅 
```ts
contextBridge.exposeInMainWorld('__SENTRY_IPC__', {
    sendScope: (scopeJson: unknown) => ipcRenderer.send(IPCChannel.SCOPE, scopeJson),
    sendEvent: (eventJson: unknown) => ipcRenderer.send(IPCChannel.EVENT, eventJson),
});
```

**Comment by timfish** [comment]
You should only need to `import '@sentry/electron/preload';` at the top of your existing preload script.

My profiling of a bundled app suggests that the entire app startup including `init` of the Electron SDK completes in under 90ms.

![image](https://user-images.githubusercontent.com/1150298/155572834-1e0a3af5-d11c-4709-8588-0ae323ef27b0.png)

If you are able to capture a startup CPU profile, I can take a closer look.

- Start your app/Electron with `--inspect-brk` 
- Open Chrome and go to `chrome://inspect`
- Click the `Open dedicated DevTools for Node` link
- This should auto-connect to your app with a breakpoint at the very start of execution
- Go to the `Profiler` tab and click `Start` and the app should startup
- Give the app a few seconds to finish starting and click stop
- Export the CPU profile

You can email it to me if you don't want to post the resulting capture here.

**Comment by timfish** [comment]
@toxik has sent me a CPU profile and it looks like the Electron `crashReporter.start()` call takes 500ms to return on macOS. 

You can avoid this for now by disabling native crash reporting which can be achieved by removing the `SentryMinidump` integration.

I've reported this issue to Electron since this is a large regression between Electron v11 to v12:
https://github.com/electron/electron/issues/33072

**Comment by toxik** [comment]
I'm closing this since it's not caused directly by the Sentry SDK. Thanks a lot, @timfish!
