### ISSUE TITLE
Sentry cannot be closed once init was called

### ISSUE THREAD

**Issue by phellmayr1** [getsentry/sentry-electron#465]
**Versions + Platform**

- SDK version - @sentry/electron@v3.x.y
- Electron version - all
- Platform - all

**Description**
I would like to close/disable sentry crash reporting after it was initialized (e.g. if the user disallows it for privacy reasons).

Closing Sentry is possible when using @sentry/angular, there you can just call `Sentry.close()`.
Sadly this `Sentry.close()` does not exist for @sentry/electron (and therefore also not in @sentry/electron/main and @sentry/electron/renderer)

Would it be possible to provide this functionality?
Or are there some known workarounds?

**Comment by timfish** [comment]
> We should maybe export close from both main/renderer index files.

It would only disable the SDK fully if you did it from the main process since that's where everything is sent from.
You can disable event submission via the `beforeSend` hook but this won't stop transactions.

One minor stumbling block is that the Electron `crashReporter` cannot be stopped once it's been started so we'll need to add some checks in the crash handling and skip out if `enabled == true`.
