### ISSUE TITLE
Events caught from renderer process by @sentry/electron do not work well

### ISSUE THREAD

**Issue by xuxunsheng** [getsentry/sentry-electron#475]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.7`
- [x] Electron version - `electron@v18.1.0`
- [x] Platform - `macOS`

## Description

Dear sentry team, I have trouble in configuring sentry for my electron-webpack-typescript-react project.
1. After i config sentry.init in renderer process and throw an error, the console.log looks like below. It shows that  An event processor returned null, will not send event. But actually the sentry server has received event from that.
![image](https://user-images.githubusercontent.com/30545946/165238243-2d52e50b-f805-45e4-9c21-fae9271d75ea.png)

2. It seems that the event from renderer may lack some attributes, which the path in event is not show in the server.
![image](https://user-images.githubusercontent.com/30545946/165242559-ce47ba04-dd9a-4ca8-a1e7-53a2b15b6dd1.png)

renderer config code:
``` javascript
console.log(
  '👋 This message is being logged by "renderer.js", included via webpack'
);
import "./index.css";
import React from "react";
import ReactDOM from "react-dom";
import App from "./browser/App";
import * as Sentry from "@sentry/electron/renderer";

Sentry.configureScope(function (scope) {
  scope.addEventProcessor(function (event, hint) {
    // Add anything to the event here
    // returning null will drop the event
    console.log("addEventProcessor");
    console.log(event);
    return event;
  });
});

Sentry.init({
  dsn: "dsn",
  sampleRate: 1.0,
  release: "1.0.1",
  debug: true,
  beforeSend: (event) => {
    console.log("before send");
    return event;
  },
});

ReactDOM.render(<App />, document.getElementById("root"));
```
If needed, I will provide a link to the source code of my demo project.

**Comment by xuxunsheng** [comment]
The demo project link: https://github.com/xuxunsheng/Electron-webpack-ts-react-sentry

**Comment by timfish** [comment]
Thanks for the example project. I'll take a look.

It's worth noting that the warning about event processor returning null is completely expected.

In the renderer, we include the `EventToMain` integration which passes events to the main process and then returns null so that nothing else occurs on the renderer. You are only seeing this because you have `debug: true`.

**Comment by xuxunsheng** [comment]
Thanks a lot for your reply, it does help me a lot.
The most important problem need to be solved is the second. I'm not sure whether the problem is caused by my configuration or SDK.But I totally follow the document to make that configuration: https://docs.sentry.io/platforms/javascript/guides/electron/configuration/
hope for your help!

**Comment by timfish** [comment]
Sorry for the delay in looking into this but I've finally found some time to clone your repository. 

The issue is caused by throwing a string:
```ts
  setTimeout(() => {
    throw "demo1 error";
  }, 1000);
```
Although in JavaScript you can throw almost any old object or primitive, it's highly discouraged to throw anything other than an `Error` because `Error` contains the call stack of where it was thrown which is why all the information is missing. Instead you should be doing:
```ts
  setTimeout(() => {
    throw new Error("demo1 error");
  }, 1000);
```
