### ISSUE TITLE
Renderer events are not sent to Sentry

### ISSUE THREAD

**Issue by umerkk** [getsentry/sentry-electron#485]
- [X] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-electron/releases

## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.2`, `@sentry/react@6.19.0`, `@sentry/node@6.19.0`
- [x] Electron version - `electron@v13.6.3`
- [x] Platform - `macOS`

## Description

I have the Sentry SDK configured on main and working just fine. I have instrumented tracing & events and they all make their way to Sentry UI.
However, the renderer events are not being sent to the main process & eventually to Sentry.
in Console, I can see the window.__SENTRY_IPC__ is initialized and I can invoke it on devtools, and those events are captured in the main process.

Here is my config.

**CLIENT_CONFIG:**
```
CLIENT_CONFIG: {
      dsn: '',
      environment: Environment.Development,
      debug: true.
      maxBreadcrumbs: 50,
      sampleRate: 0, // Default to none
      tracesSampleRate: 0,
      attachStacktrace: true,
      autoSessionTracking: true, // Can be false as the support for electron is not there yet.
      normalizeDepth: 5, // Object depth to capture e.g. Redux
    },
```

**MAIN PROCESS:**
```
 Sentry.init({
      ...Config.APM.CLIENT_CONFIG,
      release: `${systemInfo.hubVersion()}`,
      integrations: (defaultIntegrations: Integration[]) => [
        ...defaultIntegrations,
        new CaptureConsole({ levels: ['error'] }),
        new ExtraErrorData({ depth: 3 }),
        new Offline({ maxStoredEvents: 20 }),
        new Transaction(),
        new SentryNodeIntegrations.Http({ tracing: true }),
      ],
      beforeSend: this.beforeSendHandler,
    });
````

PRELOAD SCRIPT:
````
ipcRenderer.invoke('config/environmentConfig').then((Config) => {
  Sentry.init({
    ...Config.APM.CLIENT_CONFIG,
    integrations: (defaultIntegrations) => [
      ...defaultIntegrations,
      new TracingIntegrations.BrowserTracing({
        tracingOrigins: ['localhost'],
      }),
    ],
  });
});
````

I am using @Sentry/React in the renderer to capture react specific data, however instrumenting a specific exception (uncaight * sentry.captureMessage/ Sentry.captureException) both does not work and the event is lost somewhere and doesn't reach the `beforeSendHandler` and to Sentry.

Here is the screenshot of renderer devtool showing the SDK is initialized

![Screen Shot 2022-05-12 at 11 37 46 AM](https://user-images.githubusercontent.com/16906595/168114062-60bcd59c-1416-44c0-9dc8-3476095e3238.png)

![Screen Shot 2022-05-12 at 11 38 49 AM](https://user-images.githubusercontent.com/16906595/168114277-b02721ee-ee9b-4453-9cbf-91052ef2c725.png)

![Screen Shot 2022-05-12 at 11 39 47 AM](https://user-images.githubusercontent.com/16906595/168114500-7d951b71-4675-4428-8d84-c417f01f0067.png)

![Screen Shot 2022-05-12 at 11 40 02 AM](https://user-images.githubusercontent.com/16906595/168114540-5457a983-1e50-4f97-8ccf-fe6b36e97928.png)

**Comment by timfish** [comment]
I'm not entirely sure what is going on here but a few things look suspect.

- `sampleRate: 0` implies no events will be sent
- What `Offline` integration are you using there in the main process?
   - The Electron SDK >= v3 has built in offline support with the default transport
   - The `Offline` integration from Sentry uses `localStorage` which isn't available in node.js
- Ideally you want to be starting the SDK as early as possible in each process. The IPC round-trip in the renderer will mean that you won't see any errors reported that occur before the IPC `invoke` has completed
- You do not need to pass any options to the renderer `init` for basic features to work because everything is sent via the main process
   - For example, our example apps don't pass `dsn`, `environment`, etc:
https://github.com/getsentry/sentry-electron/blob/05702051d70a8ba0adb8e825ee54a83b5c7035f9/examples/webpack-context-isolation/src/renderer.js#L2-L6
   - `autoSessionTracking: true` in the renders will cause them to send browser sessions **in addition to** the default main process sessions
https://github.com/getsentry/sentry-electron/blob/05702051d70a8ba0adb8e825ee54a83b5c7035f9/src/renderer/sdk.ts#L29-L33


Here is the renderer code for the e2e test that checks browser tracing with very little configuration supplied:
https://github.com/getsentry/sentry-electron/blob/05702051d70a8ba0adb8e825ee54a83b5c7035f9/test/e2e/test-apps/other/browser-tracing/src/index.html#L8-L15

**Comment by umerkk** [comment]
Hi.
Thanks for the reply.

So, my sampleSize & tracesSampleRate are overwritten later on and is set to `1` and my main process events are being sent to Sentry (as a confirmation).

My SDK initialization happens in `preload script` which is the earliest I can load in Electron.  I can confirm from the dev tools logs that the sentry is initialized before I reach the areas of my renderer that emits those errors.

I did removed the IPC call and move the Sentry init outside the IPC call, however I do not think it works great, but I am seeing that sentry is passing a dummy DSN.

Preload.js
```
Sentry.init({
  debug: true,
  integrations: [new TracingIntegrations.BrowserTracing()],
  tracesSampleRate: 1,
  sampleRate: 1,
});
```
![Screen Shot 2022-05-16 at 10 04 16 AM](https://user-images.githubusercontent.com/16906595/168623617-286ffc3f-46bb-408a-ab3d-5c807c6d4908.png)


Despite all of that, the main process is not receiving the renderer events although the `window.___SENTRY_IPC___` exists and I can invoke it manually  through console.

Is there any debug tips that could help me identify whats the issue is?

**Comment by timfish** [comment]
Very strange that it's still trying to POST the event from the renderer even with the `EventToMain` integration correctly enabled. Without being able to debug it locally I can't be sure why.

I would start by copying the most basic code from one of the examples and slowly add your custom code until it stops working. If you can share a repository with me I'll be happy to take a look!

**Comment by timfish** [comment]
If you're renderers have `contextIsolation` enabled (which has been the default since maybe Electron v12?) then you will need to init the SDK in the preload AND isolated browser context since the two are completely isolated. 

If you have no other preload code, you can safely skip initialising there because there won't be any errors to report.
