### ISSUE TITLE
Feature request: ability to explicitly control offline mode

### ISSUE THREAD

**Issue by johnwchadwick** [getsentry/sentry-electron#489]
We have an application where we want to withhold network requests until/unless consent is given. To that end, it is possible today to implement a `beforeSend` hook that simply drops events, but this is unideal, as it would also drop events while our app is still loading and the settings model is inaccessible. In addition, it isn't entirely clear to me whether beforeSend is called before *every* network request; for example, are minidump uploads covered by this?

Assuming that Sentry will not attempt to make any kind of network requests outside of the Transport implementation that gets passed in, it is possible to implement this by simply making a transport which queues requests until we have consent given. And in fact, it seems like all of the functionality necessary to implement this already exists in `ElectronOfflineNetTransport`, but there is no possible way to adjust the `maybeOnline` check to include additional bits. So today, you would have to copy this code out and vendor it just to add this small capability.

I have a just a few questions that I would be very appreciative to have answered:

* Does every single network request to the Sentry service go through Transport? (i.e. could we _fully block_ network traffic using only this mechanism?)

* If so, would you accept pull requests for some sort of mechanism that lets us control when the `ElectronOfflineNetTransport` decides to queue? Not sure exactly how. It could be as simple as making the `maybeOnline` function a protected method of the class that can be overridden.

* If not, is there a better way I can accomplish what I want? Or is it best to simply vendor the `ElectronOfflineNetTransport` and modify it slightly?

I hope my feature request/questions are clear enough. Thanks!

**Comment by timfish** [comment]
I'm [in the process](https://github.com/getsentry/sentry-electron/pull/471) of rewriting the transports to update the underlying JavaScript SDKs to v7.

Currently, `beforeSend` only lets you intercept/stop events and not transactions. The only way to disable the SDK fully is to call `close()`.

I do like the idea of disabling the SDK via a queued transport though because this would still collect the last X events and allow users to enable sending later after they've encountered an issue. Adding this as a feature would mean just adding an optional hook to the offline transport.

**Comment by timfish** [comment]
This is now available in the latest beta release. The transports have been refactored to match the the JavaScript v7 functional style. The offline transport has an option which can be set to a function.

```ts
type BeforeSendResponse = 'send' | 'queue' | 'drop';

export interface ElectronOfflineTransportOptions extends ElectronNetTransportOptions {
  beforeSend?: (request: TransportRequest) => BeforeSendResponse;
}
```

Your function gets passed a `request` which is a raw request. This isn't very useful other than to check the size of the request but it's available at that point so it seemed worth passing. 

You would use it like this in the main process:
```ts
import { init } from '@sentry/electron/main';

function isEnabled(req): boolean {
  // check if the user has enabled error reporting
}

init({
  dsn: '__DSN__',
  transport: makeElectronOfflineTransport({
    beforeSend: (req) => {
      return isEnabled() ? 'send' : 'queue';
    }
  })
});
```

Now I'm writing this I'm realising it would be better if `beforeSend` could be async, since the only reliable way I know to store settings in Electron is via files.

I will change this for the next beta release!

Either way, you should probably be caching the user preference since reading a file every time is less than ideal!
