### ISSUE TITLE
preload script must have absolute path

### ISSUE THREAD

**Issue by anonrig** [getsentry/sentry-electron#491]
## Versions + Platform

- [x] SDK version - `@sentry/electron@v3.0.7`
- [x] Electron version - `electron@v18.2.0`
- [x] Platform - `macOS`

## Description

There are lots of error messages coming from the main process:

```
[22375:0526/171429.459534:ERROR:session_preferences.cc(38)] preload script must have absolute path: ../../common/temp/node_modules/.pnpm/@sentry+electron@3.0.7/node_modules/@sentry/electron/esm/preload/index.js
```

<img width="1616" alt="Screen Shot 2022-05-26 at 5 16 58 PM" src="https://user-images.githubusercontent.com/1935246/170581626-978727eb-e5d1-494e-bb33-d25098a52f0d.png">

**Comment by timfish** [comment]
Are you bundling your main process JavaScript code?

**Comment by anonrig** [comment]
Yes, we're using Webpack.

**Comment by damienallen** [comment]
Also using webpack for main/rendering and seeing this issue (v3.0.7). Seemed to be caused by this function being supplied with a relative path when it requires absolute:

https://github.com/getsentry/sentry-electron/blob/184272de828664629f495cdf14f63018ab195245/src/main/integrations/preload-injection.ts#L56

**Comment by damienallen** [comment]
Interesting, I will poke around to see if something can be done on the webpack config side. FYI, tere's what my webpack bundle looks like with the relative paths:

```js
_addPreloadToSessions(options) {
        let path = undefined;
        try {
            path = (0,_electron_normalize__WEBPACK_IMPORTED_MODULE_3__.rendererRequiresCrashReporterStart)()
                ? /*require.resolve*/(/*! ../../preload/legacy.js */ "./node_modules/@sentry/electron/esm/preload/legacy.js")
                : /*require.resolve*/(/*! ../../preload/index.js */ "./node_modules/@sentry/electron/esm/preload/index.js");
        }
        catch (_) {
            //
        }
        if (path && typeof path === 'string' && (0,fs__WEBPACK_IMPORTED_MODULE_1__.existsSync)(path)) {
            for (const sesh of options.getSessions()) {
                // Fetch any existing preloads so we don't overwrite them
                const existing = sesh.getPreloads();
                sesh.setPreloads([path, ...existing]);
            }
        }
        else {
            _sentry_utils__WEBPACK_IMPORTED_MODULE_5__.logger.log('The preload script could not be injected automatically. This is most likely caused by bundling of the main process');
        }
    }
```

**Comment by timfish** [comment]
Ah, so it looks like webpack does replace these with relative strings!

> I will poke around to see if something can be done on the webpack config side

It would be nice to fix this regardless of webpack config. 

Because the main process is bundled, these files will not exist and the SDK will fall back to using a custom protocol so you can avoid this for now by setting the `IPCMode` manually:
https://github.com/getsentry/sentry-electron/blob/00e7a4608e452d4447cc50cadef682af6cda6e28/test/e2e/test-apps/javascript/renderer-error-protocol/src/main.js#L9

We could convert the relative path to absolute, but because the file does not exist it will result in unnecessary file system access.

**Comment by damienallen** [comment]
Sounds like us webpack folk have to use the custom protocol either way for now, so being able to avoid this relative path is great. Your suggestion worked flawlessly for me!

Many thanks 🙌🏽
---

_main.js_
```js
import { IPCMode, init } from '@sentry/electron/main'


init({
    ...
    ipcMode: IPCMode.Protocol,
})
```
