### ISSUE TITLE
Cannot init sentry in the rendering process

### ISSUE THREAD

**Issue by Adonis-Song** [getsentry/sentry-electron#493]
## Versions + Platform

- [ ] SDK version - `@sentry/electron@v3.0.7`
- [ ] Electron version - `electron@v13.0.0`
- [ ] Platform - `macOS`

## Description

When I init sentry in the rendering process, I get this error on console.
```
Sentry SDK failed to establish connection with the Electron main process.
 - Ensure you have initialized the SDK in the main process
 - If your renderers use custom sessions, be sure to set 'getSessions' in the main process options
 - If you are bundling your main process code and using Electron < v5, you'll need to manually configure a preload script

Fetch API cannot load sentry-ipc://sentry-electron.scope/sentry_key. URL scheme "sentry-ipc" is not supported.
 ```
I don't konw why, I have done init in the main process . If I just init in the main process. Everything is OK. 
And I don't call other function

**Comment by timfish** [comment]
The Electron SDK only works if you run `init` in main AND renderer processes. 

I'm not sure why it isn't working in your case since I don't have enough information. 
- Are you using custom sessions?
- Are you calling `init` in the main process before app ready?
- Is there any error output from the main process?
- Can you supply a minimal reproduction demonstrating the issue?

**Comment by timfish** [comment]
Closing this due to no response. Feel free to re-open!
