### ISSUE TITLE
Set Device Context As a Tag

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry-electron#541]
## Description

Setting the device context as a tag instead of structured context would utilize existing features of the Issue Details page that give this data a greater visual prominence using the device badge. This is currently done with the Native SDK, as an example.

Additionally, setting the Chrome browser tag, and chrome version, results in a badge being placed on the event with the following details: "Chrome: Version Unknown". Can this be enhanced from the SDK side somehow?

**Comment by AbhiPrasad** [comment]
So generally the philosophy here is that the SDK avoids settings tags as much as possible - and we instead use context + promoting context -> tags in event ingestion (similar to what we do with browser, environment, release).

This is how we see it currently: 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/18689448/187244342-19ad722a-5634-4239-bf72-b43b54386fa8.png">

Specifically what device context are you looking to get promoted as tags?

**Comment by souredoutlook** [comment]
Hi @AbhiPrasad thanks for the follow up - here are some additional notes:

- In the screenshot you've shared I can see that we're setting `browser.name` as simply "Chrome" and then a `chrome` tag with a 4-part SemVer value for the Chrome version.  I believe the information in the `chrome` tag would typically live in the `browser` tag, but I am not sure we'd parse that version on the frontend properly.
- In the attached screenshot you can see where the device context is being set as a tag sentry-native, we store this, but only as Structured Context in sentry-electron.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/76002357/187254267-cb1b6261-5e86-475d-b71e-a2428a02e355.png">

**Comment by timfish** [comment]
> I can see that we're setting browser.name as simply "Chrome" and then a chrome tag with a 4-part SemVer value for the Chrome version. I believe the information in the chrome tag would typically live in the browser tag, but I am not sure we'd parse that version on the frontend properly

In the Electron SDK I seem to remember that we don't set the browser context fully because that caused events to be displayed as a browser events rather than Electron. I don't know whether this would still be the case and I can't find the code comment that used to describe this decision.

**Comment by wasnotrice** [comment]
@AbhiPrasad I think this issue stems from a support request I submitted. 

I have a project with both an Electron app and a native app, each with their own Sentry project. The native app shows these badges 

<img width="324" alt="image" src="https://user-images.githubusercontent.com/908/187306992-dd2c158f-4d1c-43e9-b3c7-3b6c0b0ce38e.png">

The Electron app shows these badges
<img width="522" alt="image" src="https://user-images.githubusercontent.com/908/187307224-b7ce8c08-8d54-4cee-a53c-cfc16a32a1a0.png">

I was hoping to remove the Chrome badge (it's not helpful, since it has no useful information, and there is already an Electron badge that essentially gives me the Chrome version), and add a Device badge with model and architecture as seen in the native project (here I care more about the architecture than the model).

I guess that means I'm looking for Chrome to be "demoted", and "device" or "device.model" + "device.arch" to be "promoted".

**Comment by timfish** [comment]
You can modify events to remove keys from `contexts` using `beforeSend` in the main process. I'm not sure whether this will be enough to get the events displaying as you want. You may also need to remove `node` too.

```ts
init({
  dsn: '__DSN__',
  beforeSend: (event) => {
    if(events?.contexts?.chrome) {
      delete events.contexts.chrome
    }

    if(events?.contexts?.browser) {
      delete events.contexts.browser
    }

    return event;
  }
});
```

**Comment by AbhiPrasad** [comment]
Closing this issue for cleanup. Please re-open if this still applies. Thanks!
