### ISSUE TITLE
[Sentry slowing down app] Capturing a large warning each frame will take longer than a single frames duration

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry-electron#602]
- [x] Review the documentation: https://docs.sentry.io/platforms/javascript/electron/
- [x] Search for existing issues: https://github.com/getsentry/sentry-electron/issues
- [ ] Use the latest release: https://github.com/getsentry/sentry-electron/releases **using 4.1.0**
- [ ] Provide a link to the affected event from your Sentry account

## Versions + Platform

- [x] SDK version - `@sentry/electron@v4.1.0`
- [ ] Electron version - `electron@v?.?.?`
- [ ] Platform - `Windows/macOS/Linux`

## Description

Following up with this tweet: https://twitter.com/pie6k/status/1598640700437970944

> Sentry made my app really slow.
>
>I had a warning that included a large object. It was shown on each frame while dragging. Sentry needed 60ms to capture it which is way more than 1 frame.
>
>I think 'capture' console should have a deadline max duration of capturing
Image

![image](https://user-images.githubusercontent.com/76002357/205346125-82116ef0-e195-4c15-bf84-d564c5d9915b.png)

> [...] Versions of imported libs 4.1.0 and 7.17.3

![image](https://user-images.githubusercontent.com/76002357/205346154-d0d41e03-b33f-48ef-b698-3c373a574ef8.png)

## Brainstorm

From the customer:

> I think 'capture' console should have a deadline max duration of capturing

My thoughts below are additional and have not been expressed by the original reporter:

The [CaptureConsole integration](https://docs.sentry.io/platforms/javascript/guides/electron/configuration/integrations/plugin/#captureconsole) allows specific levels of logs to be excluded using a "head based" sampling strategy. Otherwise the only option to drop specific messages or exceptions is to use the tail-based options the SDK provides (beforeSend, dedupe integration) which would not solve the latency issue. Some kind of head based de-duplication might have been helpful in this case.

**Comment by timfish** [comment]
Which process are the breadcrumbs being captured in? How large is the object that's being logged?

The Electron SDK passes breadcrumbs from the renderer processes to the main process and to do this they need to be serialised. 

> I think 'capture' console should have a deadline max duration of capturing

JavaScript is single threaded so there is no easy way for us to cancel a task if it runs for too long. 

My understanding is that console logging large objects can cause issues with all of the JavaScript SDKs since this will fill up breadcrumbs and can cause events to exceed the maximum payload. This will also result in a large block on the event loop when the event is serialised to be sent to Sentry.

**Comment by AbhiPrasad** [comment]
Closing this issue for cleanup. Please re-open if this still applies. Thanks!
