### ISSUE TITLE
Support for Session Replay

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry-electron#606]
### Problem Statement

Allow reproducing bugs through session replay

### Solution Brainstorm

Add support to Session Replay similar to how it's done for Web: https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#readme

**Comment by AbhiPrasad** [comment]
@timfish I gave this a try before hand and was able to get the replay's sending. I think what we have to figure out here is if [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) will work on the renderer instances as expected.

**Comment by timfish** [comment]
Blockers so far: 

- Electron renderers can be detected as node if `nodeIntegration` is enabled which cause the `Replay` integration to bail out early:
```ts
  setupOnce(): void {
    if (!isBrowser()) {
      return;
    }
```

- The default Electron renderer `EventToMain` integration which passes events through the main process ends up being called and returns `null` before the Replay event processor gets called
  - Adding ordering for integrations is a fudge. More/better hooks might help here
  - Events could be passed to the main process by a transport rather than an integration but this would require parsing envelopes in the main process

- https://github.com/getsentry/sentry-javascript/pull/6576

- Error ids and replays are not getting linked up

- Replay events contain urls that should be normalised so they don't contain full paths with usernames in them
  - Passing all envelopes through the main process might be the only sensible way
