### ISSUE TITLE
Source maps missing for certain internal Electron files (browser_init.js, domain.js, events.js)

### ISSUE THREAD

**Issue by erikjalevik** [getsentry/sentry-electron#613]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/organizations/fileside/issues/3834906757

### DSN

https://bb67ea13878a4f20a6a1fb330db0f518@o1264323.ingest.sentry.io/6446898

### Steps to Reproduce

Somehow cause an error triggered from `electron/js2c/browser_init.js`.

Unfortunately I can't be more specific since the Sentry error report gives very little other information.

### Expected Result

Stacktrace to show the sources for the internal Electron files `browser_init.js`, `domain.js`, `events.js`.

I am uploading all the source maps generated by my build (Webpack), and they show up under Source Maps in Settings (see screenshot).

### Actual Result

![Screenshot 2023-01-02 at 11 51 35](https://user-images.githubusercontent.com/8722592/210222191-6e162d77-652d-4155-ac47-43fc7d33cafd.png)

![Screenshot 2023-01-02 at 11 56 04](https://user-images.githubusercontent.com/8722592/210222238-4ba9bfac-6f0b-4146-9e4a-c66014d2c034.png)

![Screenshot 2023-01-02 at 11 57 39](https://user-images.githubusercontent.com/8722592/210222408-6a8b047a-dc0c-4a32-b755-781f84a42c41.png)

**Comment by erikjalevik** [comment]
> What does the error message say?

You mean the title?

```
TypeError  <anonymous>(electron/js2c/browser_init.js)
Object has been destroyed
```

> These files are built into the Electron binary. We might be able to fetch the source file but they're minimised so not ideal. We don't include source file context for built in node modules so I'm not sure we should start doing it for Electron.

Interesting. I was hunting all over for those source files but couldn't find them. I opened the ticket because I do see them quite often in Sentry issues.

**Comment by timfish** [comment]
`Object has been destroyed` is the standard error from Electron if you make calls to a `WebContents` or `BrowserWindow` instances that have been closed or have crashed. 

In the `ElectronBreadcrumbs` integration, we patch `EventEmitter.emit` for many Electron APIs to intercept and capture breadcrumbs for Electron events.  The above stack trace starts at `electron-breadcrumbs.js` but because this is a patched function, that will not be the source. It's likely that your code is calling an Electron API that tries to interact with a destroyed window/webContents but the way we're patching means that stack trace is truncated to the point it's not much help.

Let me see if I can fix that!

**Comment by timfish** [comment]
I did some testing and the stack trace does not get truncated so it looks like this error IS coming from Electrons `browser_init.js`.

Which version of Electron is this?

**Comment by erikjalevik** [comment]
> Which version of Electron is this?

This is from version 13.6.9.

Thanks for the knowledgeable help and replies!

**Comment by timfish** [comment]
I'm not sure there's much we can do from the SDK to help with this so I'll remove the `Bug` label for now...

**Comment by timfish** [comment]
I'm going to close this since we don't display source code context for node/electron internals.
