### ISSUE TITLE
Cannot distinguish between renderer crash which is not fatal vs electron entire app crash

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry-electron#651]
### Problem Statement

Clients cannot distinguish between a renderer crash that can be captured and keep the app going vs an entire app crash.
None of our tags indicate the type of crash, can we add an indicator for that?

### Solution Brainstorm

When a crash is being submitted on the next time the user open the app maybe we can add a flag that indicates that this crash was killed the process?

**Comment by timfish** [comment]
We have the following tags:
- `event.environment` which is either `native` or `javascript`
- `event.process` which is either `browser`, `renderer` or `gpu` (`browser` is the unfortunate legacy Electron terminology for the main root node process)

A `native` crash in the main `browser` process terminates the entire app and the minidump is sent on the next app run.

A `native` crash in the `gpu` process causes a minidump to be sent immediately. Electron automatically restarts the GPU process and the user might see the windows flash blank briefly while it restarts.

A `native` crash in a `renderer` process will cause the renderer window that crashed to go blank and the minidump is sent immediately. In many simpler apps, this can be considered fatal since the app may no longer function but the app will not close unless you specifically code it to do so. I have a production Electron app that handles renderer crash events and reloads the window with the previous state. In this case, users might not even notice the crash has occurred but it's still sent to Sentry so we can track them. 

`javascript` errors in the main `browser` process usually cause the process to exit so are considered fatal too but they are sent before exit. It's worth noting that `unhandledrejection` behaviour changed in Electron v15. Before then, `unhandledrejection` would not cause the process to exit.

**Comment by yuval-sentry** [comment]
@timfish Would it be possible to add a binary for crashes?

**Comment by timfish** [comment]
Does `level: fatal` as a search query not suffice?

This should cover all native crashes and JavaScript errors in the main process.

**Comment by yuval-sentry** [comment]
We are seeing a case where event.environment:native shows up both for renderer and process crashes

**Comment by timfish** [comment]
`event.environment:native` should return all native crashes.

If you only want main process crashes can you not search for a combination:
`event.environment:native event.process: browser`

**Comment by yuval-sentry** [comment]
I can, the problem is that they are all being grouped under the same issue
I guess I will need to change the fingerprinting/grouping rules?

**Comment by timfish** [comment]
> I guess I will need to change the fingerprinting/grouping rules?

So all the native crashes are linked under a single issue? 

I'm not sure, I have not seen that before with the default Sentry configuration.

**Comment by timfish** [comment]
I'm going to close this since the `level: fatal` should cover all fatal crashes, both native and node main process. Feel free to reopen if this is not the case!

**Comment by schontz** [comment]
The problem with "fatal" is that it does not give us any insight into whether or not the whole app crashed or if it was just a process in the app. For example, when the render process crashes, it is a fatal crash, but Electron gives you hooks to handle and recover from such crashes. These are very different from fatal crashes when the app dies completely. There is not currently a way to differentiate between the two in Sentry, which is a big limitation as they are not the same category of failures.

**Comment by timfish** [comment]
Renderer crashes result in the process terminating with the loss of JavaScript context which for the vast majority of apps will be considered fatal so we can't really change the default. 

If you want to change how renderer crashes are tagged before being sent to Sentry, you can do this in the `beforeSend` hook in the main process:

```ts
import { init } from `@sentry/electron/main';

init({
  dsn: '__DSN__',
  beforeSend: (event) => {
    // override event level for native renderer crashes
    if(event.tags['event.process'] === 'renderer' && event.tags['event.environment'] === 'native') {
      event.level = 'error'; // was 'fatal'
    }
    return event;
  }
});
```

**Comment by schontz** [comment]
Good suggestion. Can we invent new error levels, or are they set in stone?

**Comment by timfish** [comment]
> Can we invent new error levels, or are they set in stone?

My understanding is that these are set in stone in the Sentry backend. 

Possible options include:
```ts
export type SeverityLevel = 'fatal' | 'error' | 'warning' | 'log' | 'info' | 'debug';
```
