### ISSUE TITLE
Do I need to use this SDK if I just want to use Sentry on the renderer process? Or can I use the normal minified browser bundle in that case?

### ISSUE THREAD

**Issue by truell20** [getsentry/sentry-electron#677]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

.

### Electron Version

.

### What platform are you using?

None

### Steps to Reproduce

.

### Expected Result

.

### Actual Result

.

**Comment by timfish** [comment]
The browser SDK will work perfectly well in the renderer process but the Electron SDK does add a lot of potentially useful context like os and device info.

The electron SDK will also give more accurate session data since it tracks the full lifetime of the app and captures errors in the main process and native crashes.
