### ISSUE TITLE
@sentry/electron 0.4.2 throwing exception twice causes the app to crash

### ISSUE THREAD

**Issue by avner-hoffmann** [getsentry/sentry-electron#72]
Hi,
I'm using @sentry/electron 0.4.2 in my electron app and directly throwing JS exception (throw 'Error') from my main process for testing usage. 
once I do so I get the followinfg message in the console:

*********************************
* SentryElectron unhandledError *
*********************************
Error
---------------------------------

The second time throwing the same exception the application crashes and I'm getting the following alert in the console:
raven@2.4.2 alert: uncaught exception after calling fatal error shutdown callback - this is bad! forcing shutdown

The app crashes only when I'm using @sentry/electron to catch exceptions, when I'm not using @sentry/electron it doesn't crash. obviously JS exceptions should not crash the application like that..

Is this issue known and solved in the current release of @sentry/electron (0.5.2)?

**Comment by jan-auer** [comment]
In Node, it is not recommended to recover from a globally unhandled exception (or promise rejection). At Sentry, we follow this convention, which is why the Node SDK will reject the second exception. The `@sentry/electron v0.5.0` changed the default behavior for this and will now exit the process after reporting the exception to Sentry.

If you are expecting exceptions, try to catch them explicitly by surrounding the code with `try { ... } catch (e) { ... }` and by handling Promise rejections. We are not currently planning to allow multiple global unhandled exceptions, but I am looping in @kamilogorek for a second opinion.

Regardless, I would highly recommend you to update to the latest release of the SDK as it contains a couple of fixes for other issues and improves context and breadcrumb handling.

**Comment by avner-hoffmann** [comment]
@jan-auer - so for version 0.4.2 the behavior is to swallow the first exception and crash the application when a second exception occur? and since version 0.5.0 it changed so each unhandled exception will crash the app ?

the thing is, that if I'm not using sentry, electron itself won't crash the application when a JS exception occurs (I'm using electron 1.8.3). If electron isn't crashing the application when a JS exception occurs I'd expect that sentry won't change this behavior, but follow it as it's implemented in electron

**Comment by jan-auer** [comment]
@avner-hoffmann v0.4.2 had a bug which led to the crash. We fixed this in v0.5.0 by using the standard behavior of Node. 

However, you have a valid point here as mentioned [this commend by zcbenz](https://github.com/electron/electron/issues/1536#issuecomment-98040978). Electron follows the io.js convention, which I strongly believe is an antipattern and should be avoided when using Sentry. I am willing to discuss changing this back to the original behavior (catching the exception without quitting the app), or otherwise documenting this part better.

**Comment by avner-hoffmann** [comment]
I just think that if Electron knows how to handle an exception without it causing the app to crash, then Sentry should follow the same pattern. If an electron native JS exception would really cause the app to crash, I'm sure it will if it justifies it, e.g. the application is left in an unclear state. But if Electron's behavior is to "protect" the user from experiencing crashes which can be avoided then it's better. 
From a user experience, a crash is the worst scenario, a bug is preferable

**Comment by avner-hoffmann** [comment]
great to hear. 
thanks!

**Comment by HazAT** [comment]
We've just released `0.7.0` which no longer causes your app by default to crash.
Note that there are some other "breaking" changes so be sure to check out the changelog.
