### ISSUE TITLE
Certain values from Electron API don't appear available in beforeSend (exit.reason)

### ISSUE THREAD

**Issue by quickstark** [getsentry/sentry-electron#722]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.1.2

### Electron Version

24.4.0

### What platform are you using?

MacOS

### Steps to Reproduce

Attempt to access Electron API supplied values in beforeSend handler.

### Expected Result

Would expect to have exit.reason and similar value present in beforeSend.

### Actual Result

Some expected values (e.g. like exit.reason) do not appear available in the context of beforeSend, but they do appear in the Sentry Issue post-ingestion. Breadcrumbs are also undefined in this context.

Below is an example of the logged values available in beforeSend. 

```
  *** handler:beforeSendHandler
event: {
sdk: {
name: 'sentry.javascript.electron',
packages: [ [Object] ],
version: '4.1.2',
integrations: [
'SentryMinidump', 'ElectronBreadcrumbs',
'Net', 'MainContext',
'ChildProcess', 'OnUncaughtException',
'PreloadInjection', 'AdditionalContext',
'Screenshots', 'InboundFilters',
'FunctionToString', 'Console',
'Http', 'OnUnhandledRejection',
'ContextLines', 'Modules',
'LinkedErrors', 'MainProcessSession'
]
},
contexts: {
app: {
app_name: 'Generic App-dev',
app_version: '5.0.0',
app_start_time: '2023-08-16T14:46:07.111Z'
},
os: {
kernel_version: '22.6.0',
name: 'macOS',
version: '13.5',
build: '22G74'
},
browser: { name: 'Chrome' },
chrome: { name: 'Chrome', type: 'runtime', version: '112.0.5615.204' },
device: {
arch: 'x64',
family: 'Desktop',
language: 'en-US',
screen_density: 1,
screen_resolution: '1920x1080',
memory_size: 17179869184,
free_memory: 5948444672,
processor_count: 12,
cpu_description: 'Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz',
processor_frequency: 2600
},
node: { name: 'Node', type: 'runtime', version: '18.14.0' },
runtime: { name: 'Electron', version: '24.4.0' },
'Enabled Features': { enabledFeatures: [Array] }
},
environment: 'macOS-local',
release: 'Generic-App-dev@5.0.0',
user: {
ip_address: '{{auto}}',
id: '5ba56bf0-9f80-4699-8eaf-7d96c4ede2c6'
},
tags: {
'event.origin': 'electron',
'event.environment': 'native',
'event.process': 'browser',
event_type: 'native',
electronSessionId: '25f04ac8-e9f9-4f86-812f-fbed856560c4',
expressStage: 'prod',
ring: 'CURRENT'
},
level: 'fatal',
platform: 'native',
breadcrumbs: undefined,
sdkProcessingMetadata: {},
modules: {},
event_id: '3391a5e0a7f741958122c63e68627a75',
timestamp: 1692197168.438
}
hint: {
attachments: [
{
attachmentType: 'event.minidump',
filename: '4d99b24f-3a2a-4bd9-b2ba-4000b5bac743.dmp',
data: <Buffer 4d 44 4d 50 93 a7 00 00 08 00 00 00 20 00 00 00 00 00 00 00 11 e1 dc 64 00 00 00 00 00 00 00 00 07 00 00 00 38 00 00 00 80 00 00 00 0f 00 00 00 40 03 ... 713582 more bytes>
}
],
event_id: '3391a5e0a7f741958122c63e68627a75'
}
```

**Comment by timfish** [comment]
Electron only gives an exit reason for the `renderer-process-gone` and `child-process-gone` events so we only have this data for renderer or child process crashes. When available we set this as the `exit.reason` tag.

`'event.process': 'browser'` in the above native crash shows that this crash came from the Electron main process. Since the app terminates immediately on main process crashes and the crash report is not sent until the next app run, we have no way to know the exact reason.

**Comment by Altaimorin** [comment]
Hi Tim, thanks for the reply. Just a quick questions:
Can we assume an event is a crash, if we got `event.process:browser` and `level: fatal` for it? Or generally what tags indicate a crash from the main process?

**Comment by timfish** [comment]
Yes, `fatal` represents a crash.

`exit.reason` is extra information about the specific type of crash and is only added when this info is available. 

For example for renderer processes, there are exit reasons `crash` and `oom` (out of memory). For both of these, the process will exit and a minidump is sent to Sentry where a stack trace will be displayed. These are both "crashes" from a user perspective.

We don't tag all native main process crashes as `exit.reason: crash` because it may well have been `oom` but Electron doesn't give us a way to determine this detail for main process crashes.

Note that uncaught JavaScript errors in the main process are also considered `level: fatal` since these also cause the app to exit. Uncaught JavaScript errors in renderer processes are `level: error` since they don't cause the app to exit.

To disambiguate between JavaScript and native crashes you can use the `event.environment` tag.

**Comment by Altaimorin** [comment]
There's a issue with using `fatal` tag for the crash metric of browser processes: We got [crash_reporter::DumpWithoutCrashing](https://amazon-chime.sentry.io/issues/4262904546/?project=6194236&query=DumpWithoutCrashing&referrer=issue-stream&statsPeriod=14d&stream_index=0) error which is tagged `fatal` but doesn't actually result in a crash. Is there any way that we cannot filter it out in the Electron code (For instance, can we obtain the name of the issue in Electron)?

**Comment by timfish** [comment]
What causes `crash_reporter::DumpWithoutCrashing`? My assumption is that this is only triggered by attaching a debugger and dumpling the memory?

**Comment by hanfangAmazon** [comment]
They are using `DUMP_WILL_BE_CHECK` in many places (previously called `DumpWithoutCrashing`)
One example is ObserverList: https://chromium.googlesource.com/chromium/src/+/807a2a6b3fb8680927bd090cf2f6ee584aae962f

https://source.chromium.org/search?q=DUMP_WILL_BE_CHECK&sq=&ss=chromium

**Comment by timfish** [comment]
I'm not sure if there's a way to filter these client side and you'd need to ignore them in Sentry.

**Comment by Altaimorin** [comment]
Can we get the issue name(like "crash_reporter::DumpWithoutCrashing") on the client side in Electron?

**Comment by timfish** [comment]
> Can we get the issue name(like "crash_reporter::DumpWithoutCrashing") on the client side in Electron?

No, this informaiton is only available after the minidump has ben parsed server side.

**Comment by timfish** [comment]
I'm going to close this for now since there is nothing we can do in the client SDK to improve this. Feel free to open new issues if you have any more questions!
