### ISSUE TITLE
Support for plugins?

### ISSUE THREAD

**Issue by dimitarnestorov** [getsentry/sentry-electron#74]
Will there be support for plugins?

Our project is in migration stage from AngularJS to React, however it will be in this stage for a lot longer.

In `raven-js` there is support for AngularJS in the form of a plugin and here's how I've been using it up until 0.4.2:
```javascript
const { SentryClient } = require('@sentry/electron');
const angular = require('angular');
const Raven = require('raven-js');
const RavenAngularJSPlugin = require('raven-js/plugins/angular');

const dsn = 'url';

if(!window.isDevMode){
	SentryClient.create({
		dsn,
		release: RELEASE
	});
	Raven.addPlugin(RavenAngularJSPlugin, angular);
}
```

If you don't plan support I'll just read the source of the `raven-js` plugin and implement error reporting in AngularJS context myself.

Not a big deal, just wanted to keep up with the latest version and bug fixes 🙂

**Comment by jan-auer** [comment]
Hi @dimitarnestorov, thanks for reporting this. 

We are planning to re-introduce plugins into the [streamlined JavaScript SDKs](https://github.com/getsentry/raven-js/tree/next#readme) with an updated and more flexible API. The design of that API has not been finalized yet, which is why I cannot give you details on an implementation roadmap.

Until then, you can manually implement the [angular plugin](https://github.com/getsentry/raven-js/blob/master/plugins/angular.js) by using the `beforeSend` option in place of `dataCallback`. Most of the other code should stay the same.

I will keep this open until we can provide the original Raven plugin functionality for Electron, as I agree as I think this is an important part of the SDK.

CC @kamilogorek

**Comment by dimitarnestorov** [comment]
What happened to [`RavenOptions`](https://github.com/getsentry/raven-js/blob/master/typescript/raven.d.ts#L10)? On https://github.com/getsentry/raven-js/blob/master/plugins/angular.js#L32 the second argument is of type `RavenOptions`.

Looking at the [AngularJS docs](https://docs.angularjs.org/api/ng/service/$exceptionHandler#$exceptionHandler-arguments) it says it's optional information about the context in which the error was thrown. Can I add `extra` as a property to the exception?
```javascript
function exceptionHandler($delegate){
	return function(ex, cause){
		ex.extra = {cause};
		captureException(ex);
		$delegate(ex, cause);
	};
}
```

**Comment by jan-auer** [comment]
You got us there 😄, this is indeed not possible in the current API. We were not aware that setting custom fields just for a single event should be part of the public API. We will have to add this. FWIW, this has nothing to do with `RavenOptions`, which are still there (as `ElectronOptions` in this case). 

Until then, there is a rather cumbersome workaround by using `setExtraContext`.

**Comment by dimitarnestorov** [comment]
Is that what you meant by cumbersome? Also is that to way to clear the context?
```javascript
exceptionHandler.$inject = ['$delegate'];
function exceptionHandler($delegate){
	return function(ex, cause){
		setExtraContext({cause});
		captureException(ex);
		setExtraContext({cause: null});
		$delegate(ex, cause);
	};
}
```

**Comment by jan-auer** [comment]
That is exactly what I meant by cumbersome 😄 Thanks for providing this implementation. 

I will leave this issue open until we provide an official API for integrations.

**Comment by dimitarnestorov** [comment]
So I had to make some changes (all of them can be seen in the revisions tab of the gist). I moved the `beforeSend` handler from the renderer to the main process, since errors are being processed by the main process. Can I propose that `init` throws in the renderer process if `beforeSend` is sent as an option, and points the user towards moving it in the main process?

Also do you mind if a separate issue "`captureException` with one-time extra context" is opened? Would love to track that.

**Comment by HazAT** [comment]
So we introduced a new concept called `integrations`.
They are very powerful and can change events before sending it to Sentry see for example:
https://github.com/getsentry/sentry-electron/blob/master/src/main/integrations/onuncaughtexception.ts

They have to conform this simple interface:
https://github.com/getsentry/raven-js/blob/master/packages/types/src/index.ts#L150

Of course, you can add your custom integrations like:
```javascript
Sentry.init({
  dsn: "DSN",
  integrations: (integrations) => {
    integrations.push(new MyCustomAngularIntegration(angular));
  });
```
This will preseve default integrations and just add your custom itegration.

You can also do this:
```javascript
Sentry.init({
  dsn: "DSN",
  integrations: [new MyCustomAngularIntegration(angular)]
});
```
But this is not the recommended way since you would "loose" the default integrations we recommend.

**Comment by timfish** [comment]
Integrations should now all be working. If you're having issues with any particular integration and `@sentry/electron`, please open a new issue.
