### ISSUE TITLE
Breaks during Node Processes

### ISSUE THREAD

**Issue by vhmth** [getsentry/sentry-electron#75]
I'm getting the following error:

```
TypeError: Cannot read property 'app' of undefined
    at Object.getApp (/Users/vinay/Code/desktop/node_modules/@sentry/electron/src/utils.ts:17:41)
    at Object.<anonymous> (/Users/vinay/Code/desktop/node_modules/@sentry/electron/src/normalize.ts:6:18)
```

Unfortunately, running our eslint process is triggering this error since it's invoked via `gulp` (a node proc).

**Comment by jan-auer** [comment]
You are receiving this error because the `electron` import required for running this SDK is not available in node. Could you please share some more information what your lint stage is doing exactly? 

I am noticing that eslint tries to load and execute the `@sentry/electron` package, which already sounds strange. How does it work with your own files which depend on `require('electron')`? 

However, there shouldn't be a need for you to lint your node_modules. You could for instance try to exclude them from the eslint run.

**Comment by vhmth** [comment]
@jan-auer closing because this issue is truly not your guys' responsibility. Instead, I'm now setting an env variable and checking on a conditional require. The reason this is happening is because, in my gulpfile, I'm importing a module that relies on `@sentry/electron`. It would be nice to be able to detect electron vs. node, but I'll close as "out of scope".
