### ISSUE TITLE
setUserContext doesn't work since 0.5.1

### ISSUE THREAD

**Issue by dimitarnestorov** [getsentry/sentry-electron#77]
Seems to be working correctly in 0.5.0. `setExtraContext` seems to be still working though.

**Comment by jan-auer** [comment]
Can you share some more information, please? I tried to reproduce but setting user context does work from both the main and renderer processes like this, provided you have initialized the SDK **before** calling `setUserContext`: 

```js
const { setUserContext, captureException } = require('..');

setUserContext({
  email: 'example@foo.org',
  username: 'mytestuser',
});

captureException(new Error('this will have a user set'));
```

**Comment by dimitarnestorov** [comment]
Not sure how to share an example, will reopen when I have more info to share.

**Comment by dimitarnestorov** [comment]
Of course your example will work, on 0.5.0 
Updated to 0.5.1:
![image](https://user-images.githubusercontent.com/8790386/39447528-b7f91d26-4cca-11e8-9e3b-992e49c1be4b.png)

**Comment by dimitarnestorov** [comment]
BTW I'm not using sentry.io

**Comment by jan-auer** [comment]
That's fine, it should not make a difference whether you're going to on-prem or sentry.io in this case. There's a link in the UI to look at the raw JSON payload of the events. I assume that the ones sent from 0.5.1 onwards only contain an `ip_address` in the `user` field? 

I would love to somehow reproduce this issue, since it is working for me with the latest version (0.5.3). Could you try to create a minimal reproducing example and share it with me (via email, gist or here directly)?

**Comment by dimitarnestorov** [comment]
Hope this helps: https://github.com/dimitarnestorov/lets-test-sentry

To run it:
```bash
npm install #ofcourse
DSN="URL" npm run start
```

JSON from 0.5.0: https://pastebin.com/KQ9ArmTk
JSON from 0.5.1: https://pastebin.com/bhhhCt2B

**Comment by dimitarnestorov** [comment]
Just noticed this:
![image](https://user-images.githubusercontent.com/8790386/39495574-83b21a84-4da3-11e8-8834-cb7af99e37f4.png)

**Comment by dimitarnestorov** [comment]
Added a dummy `ip_address` to setUserContext and success on 0.5.1: https://pastebin.com/qpPFR2CW

After that success I removed the `ip_address` line and seems like sentry stores it somewhere because I can receive errors from that client with different user context without re-setting the `ip_address` and it is still the dummy one.

I'm suspecting sentry.io has 2 lines of code which make it deal with `{{auto}}` and on premise doesn't have them yet?

P.S. Sorry for the spam, literally posting these messages as I'm finding stuff out.

**Comment by jan-auer** [comment]
No worries, thank you for providing all this information. AFAIK `ip_address: {{auto}}` has been added a while back. I'm really surprised that this breaks for you. Are you maybe running a sentry version even older than `8.22.0`? If so, please update your installation 😄 

I'm now gravitating towards marking this issue as `wontfix` - we will be releasing Sentry 9 [fairly soon](https://forum.sentry.io/t/8-23-release-roadmap/3705/2) and can't guarantee full Electron support for older Sentry versions anyway. 

FWIW, due to GDPR we're going to introduce an option to omit certain PII (which IP addresses might a part of), which you can then use to omit this. Until then, I would suggest to remove the `ip_address` in the `beforeSend` callback (I am aware that the IP address is actually added after invoking `beforeSend`, but that's a bug that needs fixing).

**Comment by dimitarnestorov** [comment]
I am on `8.22.0`. And thanks, your suggestion seems to do the job, `@latest` achieved.
