### ISSUE TITLE
Add support for Sentry Developer Metrics

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry-electron#803]
### Problem Statement

Sentry is introducing support for a [metrics product](https://github.com/getsentry/sentry/discussions/58584).

Spec: https://develop.sentry.dev/sdk/metrics/

This was already implemented in the JavaScript SDK:
- Browser: https://github.com/getsentry/sentry-javascript/discussions/9938
- Node: https://github.com/getsentry/sentry-javascript/discussions/9973

Min required JS SDK version: `7.91.0`

### Solution Brainstorm

Let's add this to the Electron SDK!

This should be similar to the Node SDK, so we gate the usage by `metricsAggregator` experiment.

```ts
Sentry.init({
  dsn: '__DSN__',
  _experiments: {
    metricsAggregator: true,
  },
});
```

I think the Electron Client can just use the server-runtime metrics aggregator, the renderer can just forward to the main process, and the main process client is in charge of the aggregation.

**Comment by timfish** [comment]
We currently blocked updating the JavaScript SDKs until the `scope.clone` issue is resolved

**Comment by timfish** [comment]
> the renderer can just forward to the main process, and the main process client is in charge of the aggregation

How important is it that aggregation occurs between the multiple processes? 

We can intercept the metrics envelopes sent from the renderers and pull out the array of `MetricBucketItem`, but there's no simple way to then add those to the `MetricsAggregator` since the metrics have been serialised at this point. We'd either need to parse the serialised metrics or add a `beforeMetricAdd` hook so that they could be passed via IPC and added in main process individually.

My guess is that it wouldn't be that common to submit the same metrics from different processes anyway and we could just pass the metric envelopes straight through the main process, much like we do already for replay envelopes.

**Comment by AbhiPrasad** [comment]
> How important is it that aggregation occurs between the multiple processes?

I think this is required, given we want to minimize the amount of envelopes sent to Sentry as much as possible. I think `beforeMetricAdd` + IPC seems reasonable as an approach to use, and rely completely on the main process to flush.

Does an interval flushing mechanism work fine for electron?

**Comment by timfish** [comment]
Actually I don't think we need to add a `beforeMetricAdd` hook to the client. We can replace the `eventAggregator` in the render/browser and when `add` is called we can forward over IPC.
