### ISSUE TITLE
The ANR worker only functions correctly on the first ANR

### ISSUE THREAD

**Issue by PayneFuRC** [getsentry/sentry-electron#876]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Electron SDK Version

4.22.0

### Electron Version

29.2.0

### What platform are you using?

MacOS

### Steps to Reproduce

1. run the example app: https://gist.github.com/PayneFuRC/52c3ccb46d0a306d84600213c1e09cdb
2. input some text, then the main process will be freeze.
3. The anr info will be uploaded to sentry
4. After resume, then input some text again, the main process will be freeze again
5. The anr info will be not uploaded

### Expected Result

The second ANR info will be uploaded

### Actual Result

The second ANR info will not be uploaded

**Comment by timfish** [comment]
This is currently the expected behaviour. 

Related: https://github.com/getsentry/sentry-javascript/issues/11160

Since the ANR worker does not run a full SDK, there is no event deduplication and we wanted to avoid sending unlimited events and using up quotas when the feature was first released.

I'll look into adding a setting to allow events to be sent.
