### ISSUE TITLE
shouldSend not working

### ISSUE THREAD

**Issue by rodrigopavezi** [getsentry/sentry-electron#88]
I have setup sentry for electron with a shouldSend that will only send events if user has agreed on it. This is the code:

```
const { init } = require('@sentry/electron');
const guideSettings = require('./models/guide-setting')();
const log = require("electron-log");
const sentry = require('../assets/data/sentry');

const shouldSendIfAgreed = async () => {
	const result = await guideSettings.findAll();
	log.info("crashReportAgreement", result[0].crashReportAgreement); // prints 0
	// return (result[0].crashReportAgreement === 1)
	return false;
}

module.exports = {
	startCrashReport: async () => {
		log.info("Starting Crash Report")
		init({
			dsn: sentry.dsn,
			shouldSend: (data) => {
				return shouldSendIfAgreed();		
			}
		});
		return;
	}
};
```

So I commented out the actual condicional and changed it to false. Even though, it will not stop sentry to send the error event.

Is there anything I need to do that is not being done on this code or there is actually a bug?

Cheers

**Comment by jan-auer** [comment]
`shouldSend` is a synchronous callback. Since your async implementation effectively returns a truthy value (the `Promise`), it will always send, regardless of what the Promise resolves to. Return a boolean synchronously and the callback will work as expected.

To do so, you will probably have to externally manage a flag. Also, beware that by marking the `startCrashReport` function `async`, its execution might be deferred and enable the crashReporter too late to catch errors happening in the first event loop cycle(s). There's actually no reason this function is async.

```js
const { init } = require('@sentry/electron');
const guideSettings = require('./models/guide-setting')();
const log = require("electron-log");
const sentry = require('../assets/data/sentry');

// assume the user has not agreed until settings have loaded
let agreed = false;

async function loadAgreement() {
	const result = await guideSettings.findAll();
	agreed = result[0].crashReportAgreement === 1;
	log.info("crashReportAgreement", agreed);
}

module.exports = {
	startCrashReport: () => {
		log.info("Starting Crash Report")
		init({
			dsn: sentry.dsn,
			shouldSend: () => agreed,
		});

		// prevent unhandled promise rejections here
                 // alternatively await here and catch the rejection at the call site
		loadAgreement().catch(e => log.error(e));
	}
};
```
