### ISSUE TITLE
navigator.mediaDevices is undefined when i using sentry

### ISSUE THREAD

**Issue by 0xlau** [getsentry/sentry-electron#948]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Create Element App
2. Init Sentry
3. Call navigator.mediaDevices

### Expected Result

navigator.mediaDevices is not undefined.

### Actual Result

![img_v3_02ck_d8c5883d-61da-4155-847b-0e66bf0362cg](https://github.com/getsentry/sentry/assets/45397727/ac2bfbe5-9db7-4466-b486-a277e6d7ffce)

### Product Area

Issues

**Comment by 0xlau** [comment]
I try to migrate to v8.x. But it still does not work about the `missing mediaDevices` problem.

```json
    "@sentry/browser": "^8.17.0",
    "@sentry/core": "^8.17.0",
    "@sentry/electron": "^5.2.0",
    "@sentry/react": "^8.17.0",
    "@sentry/vite-plugin": "^2.21.0",
```

But I found that if I run `npm run start` in the development environment, navigator.mediaDevices exist, but once I package, navigator doesn't exist.

**Comment by AbhiPrasad** [comment]
@0xlau are you able to reproduce this in a barebones electron app? That would help us understand what is happening, unfortunately even with your versions + sdk setup I was unable to reproduce.

**Comment by 0xlau** [comment]
@AbhiPrasad Hey 👋, You can download this project to reproduce this issue.
[min-error-sentry-reproduction.zip](https://github.com/user-attachments/files/16215883/min-error-sentry-reproduction.zip)

**Comment by timfish** [comment]
I've managed to reproduce the issue with the supplied reproduction and I think it has something to do with custom protocols but I don't know the exact cause yet.  

For now you might be able to work aroud this in two different ways:

## Load your renderer content using `file://` urls rather than a custom protocol

You can load your source files into the renderers via `file:` URLs and the custom protocol isn't usually required to do this.

## Use "Classic" IPC for Sentry communications

If classic IPC cannot be configured (usually due to bundling), the Sentry SDK reverts to using a custom protocol to communicate between renderers and main process. You can force classic IPC by including Sentrys preload hookup code in the top of your preload file:

`preload.ts`
```ts
import '@sentry/electron/preload';
```

and then disable the Sentry custom protcol setup with the following init option:
```ts
import * as Sentry from '@sentry/electron/main';

Sentry.init({
  dsn: '__DSN__',
  ipcMode: Sentry.IPCMode.Classic, // <- this disables the Sentry custom protocol
});
```

**Comment by timfish** [comment]
Yep, confirmed that loading the renderer via file URL in production works around the issue:
```ts
    const url = pathToFileURL(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`),
    );
    mainWindow.loadURL(url.href);
```

**Comment by 0xlau** [comment]
@timfish @AbhiPrasad 
> Use "Classic" IPC for Sentry communications

It works fine!
I truly appreciate your timely help.
