### ISSUE TITLE
Is there a way to add some common tags for metrics.

### ISSUE THREAD

**Issue by CurryYangxx** [getsentry/sentry-electron#956]
### Problem Statement

Currently if we want to add some common tags for metrics such as os or browser, we need to add every time when report a metric, is there a way to add common tags for metrics once? Like the way we set tags for errors.
```
Sentry.metrics.distribution("component_load_time", 15.0, {
  tags: { os: "windows" },
  unit: "millisecond",
});
```

### Solution Brainstorm

Support a function to set common tags for metric.

**Comment by Lms24** [comment]
Hi @CurryYangxx at this time, there is no way to set tags more globally for metrics. Apologies for the inconvenience. 

Heads-up: We're making some [changes to the metrics product](https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Upcoming-API-Changes-to-Metrics) which most likely will also affect how you use the SDK to send metrics. For the moment, we're not yet 100% sure how the SDK API changes will work so we're not going to make changes to the current API.

I'm going to close this issue because we're still waiting on API decisions. Please let me know if you have more questions.
