### ISSUE TITLE
Importing "@sentry/electron/main" with "type": "module" in my package.json breaks the build

### ISSUE THREAD

**Issue by jeffreymb** [getsentry/sentry-electron#992]
### Is there an existing issue for this?

- [x] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [x] I have reviewed the documentation https://docs.sentry.io/
- [x] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Electron SDK Version

5.4.0

### Electron Version

32.0.2

### What platform are you using?

Windows

### Steps to Reproduce

In my package.json I have "type": "module". I'm configuring Sentry in my `main.ts` as follows:

```
import * as Sentry from '@sentry/electron/main';

Sentry.init({
  enabled: false,
  dsn: 'https://*****@sentry.***.com/6',
  transportOptions: {
    maxAgeDays: 15,
    maxQueueSize: 30,
    flushAtStartup: true,
  },
});
```

I am using electron-vite for the build process.

### Expected Result

A functional build.

### Actual Result

When I do this, I get the following error:
```
App threw an error during load
ReferenceError: __dirname is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '**\**\client\package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
at file:///**/**/client/dist/main/index.js:86:19
```

The line that the errors points to is an import generated by the vite build process that looks like this: `const icon = join(__dirname, "./chunks/icon-CKrYYyr5.png");` It is imported in Typescript like this: `import icon from '../../build/icon.png?asset';` from `client/src/main.ts`

Whenever I remove Sentry, everything works as expected.

**Comment by timfish** [comment]
We don't use `__dirname` in this SDK and the e2e tests cover testing with ESM main process code.

I'm not sure what's causing this and I'd be surprised if this SDK is the root cause, especially since the error is pointing elsewhere. With a minimal reproduction repository I could certainly look into this further!

**Comment by jeffreymb** [comment]
@timfish This repo: https://github.com/jeffreymb/electron_vite_sentry demonstrates the issue.

**Comment by timfish** [comment]
This is a bug with the [electron-vite esm plugin](https://github.com/alex8088/electron-vite/blob/bf1220875f0164055e8b2d9039bffdbdc6b274d2/src/plugins/esm.ts).

`__dirname` is not normally available in ESM but the above vite plugin injects shims so they are available. Due to a bug in the plugin, when Sentry is imported it can no longer work out where the imports end and where to [inject the shims](https://github.com/alex8088/electron-vite/blob/bf1220875f0164055e8b2d9039bffdbdc6b274d2/src/plugins/esm.ts#L26-L30) and it silently fails. This means that when you try and use `__dirname` it does not exist.
